### PR TITLE
Updates for latest version of Discord.py

### PR DESCRIPTION
**Pull request by codetheweb**
Tapir Bot lives again!

Mostly updates to get it working with the latest version of Discord.py. Also:

- Adds `requirements.txt`
- Moves token for Synoptic to `credentials.json`

Every command has been tested.

### CODE REVIEW

**Comment by RossSmyth** [comment]
Looks fine after a scroll through.

**Comment by RossSmyth** [comment]
Could you squash your commits though

**Comment by codetheweb** [comment]
There should be a way to [squash commits when merging](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuring-commit-squashing-for-pull-requests).

**Comment by RossSmyth** [comment]
This fixes #11

**Pull request merged**
